export const FUTURAMA = '/futurama'
export const FUTURAMA_CHARACTERS = '/futurama/characters'
export const FUTURAMA_CHARACTERS_INFO = '/futurama/characters/characters:id'
export const FUTURAMA_CAST = '/futurama/cast'
export const FUTURAMA_EPISODES = '/futurama/episodes'
export const FUTURAMA_EPISODE_ID = '/futurama/episodes/episod:id'